#! /bin/bash

set -e
. $HOME/.farmrc

# MadWifi
if test -d tools; then
	target=modules
fi

# ndiswrapper
if test -d utils; then
	target=driver
fi

error=
for bintree in $farmbin/*; do
	arch=
	if test -r $bintree/configured-i386; then
		arch=i386
		ccflags=-m32
	fi
	if test -r $bintree/configured-x86_64; then
		arch=x86_64
		ccflags=-m64
	fi
	test -n "$arch" || continue
	log=Log-`basename $bintree`
	rm -f $log $log-ok $log-error
	$make clean KERNELRELEASE=0 VERSION_HEADER=. >/dev/null
	echo -n "Checking $bintree "
	if $make HOSTCC="$ucc $ucflags" CC="$kcc $ccflags" \
	     ARCH=$arch KBUILD=$bintree KERNELPATH=$bintree \
	     KERNEL_PATH=$bintree C=2 CF="-D__CHECK_ENDIAN__" \
	     $target >$log 2>&1; then
		mv $log $log-ok
		echo -e "\e[32mOK\e[0m"
	else
		error=1
		mv $log $log-error
		echo -e "\e[31mERROR\e[0m"
	fi
done

if test -z "$error"; then
		echo -e "\e[32mAll OK\e[0m"
		exit 0
	else
		echo -e "\e[31mErrors found\e[0m"
		exit 1
fi
