#! /bin/bash

set -e
. $HOME/.farmrc

cd $linuxgit
mkdir -p $farmsrc
error=
for tag in $tags; do
	srctree=$farmsrc/$(echo $tag | sed 's,/,-,')
	echo -n "Checking out $srctree "
	if test -d $srctree; then
		echo -e "\e[33mEXISTS\e[0m"
		continue
	fi
	mkdir $srctree
	if git --work-tree=$srctree checkout $tag -- .; then
		echo -e "\e[32mOK\e[0m"
	else
		error=1
		rm -rf $srctree
		echo -e "\e[31mERROR\e[0m"
	fi
done

if test -z "$error"; then
		echo -e "\e[32mAll OK\e[0m"
		exit 0
	else
		echo -e "\e[31mErrors found\e[0m"
		exit 1
fi
