#! /bin/bash

set -e
trap 'echo -e "\e[31mUnexpected failure, terminated!\e[0m"' exit
. $HOME/.farmrc

mkdir -p $farmsrc
mkdir -p $farmgit
error=
for tag in $tags; do
	dirname=$(echo $tag | sed 's,/,-,')
	srctree=$farmsrc/$dirname
	gittree=$farmgit/$dirname
	echo -n "Checking out $srctree "
	if test -d $srctree && test -d $gittree; then
		if myrev=$(git --git-dir=$gittree rev-parse HEAD) &&
		   tagrev=$(git --git-dir=$gittree rev-parse $tag^0) &&
		   test "$myrev" = "$tagrev"; then
			echo -e "\e[36mUp to date\e[0m"
		else
			echo -e "\e[35mOut of date\e[0m"
		fi
		continue
	fi
	if rm -rf $srctree $gittree &&
	   git clone --quiet --local --mirror $linuxgit $gittree &&
	   git --bare --git-dir=$gittree config core.bare false &&
	   git --bare --git-dir=$gittree config core.worktree $srctree &&
	   cd $srctree &&
	   git --bare --git-dir=$gittree --work-tree=$srctree checkout --quiet $tag &&
	   echo "gitdir: $gittree" >$srctree/.git; then
		echo -e "\e[32mOK\e[0m"
	else
		error=1
		rm -rf $srctree
		echo -e "\e[31mERROR\e[0m"
	fi
done

trap - exit
if test -z "$error"; then
		echo -e "\e[32mAll OK\e[0m"
		exit 0
	else
		echo -e "\e[31mErrors found\e[0m"
		exit 1
fi
