#! /bin/bash

set -e

if test -n "$1"; then
	arch="$1"
else
	arch=$(uname -i)
fi

case "$arch" in
i386)
	ccflags=-m32 ;;
x86_64)
	ccflags=-m64 ;;
*)
	echo "Unsupported architecture $arch"
	exit 1 ;;
esac

trap 'echo -e "\e[31mUnexpected failure, terminated!\e[0m"' exit
. $HOME/.farmrc

error=
for srctree in $(ls -d $farmsrc/* | sort -V); do
	test -d $srctree/Documentation || continue
	bintree=$farmbin/$(basename $srctree)-$arch
	gittree=$farmgit/$(basename $srctree)
	echo -n "Configuring $bintree "
	if test -e $gittree/index &&
	   test -e $bintree/configured-$arch &&
	   test $bintree/configured-$arch -nt $gittree/index; then
		echo -e "\e[36mUp to date\e[0m"
		continue
	fi
	rm -rf $bintree
	rm -rf $bintree-bad
	mkdir -p $bintree
	cd $srctree
	cvars=
	for cvar in $config_enable; do
		cvars="$cvars $cvar=y"
	done
	$make HOSTCC="$ucc $ucflags" KBUILD_OUTPUT=$bintree $cvars \
		ARCH=$arch defconfig >$bintree/Log-config1-out \
		2>$bintree/Log-config1-err
	cd $bintree
	for cvar in $config_enable; do
		sed -i -e "s/# $cvar is not set/$cvar=y/" .config
	done
	yes "" | $make HOSTCC="$ucc $ucflags" ARCH=$arch oldconfig \
		>Log-config2-out 2>Log-config2-err
	if $make CC="$kcc $ccflags" HOSTCC="$ucc $ucflags" \
	     ARCH=$arch modules_prepare >Log-prepare-out 2>Log-prepare-err; then
		date > $bintree/configured-$arch
		echo -e "\e[32mOK\e[0m"
	else
		error=1
		cd $srctree
		mv $bintree $bintree-bad
		echo -e "\e[31mERROR\e[0m"
	fi
done

trap - exit
if test -z "$error"; then
		echo -e "\e[32mAll OK\e[0m"
		exit 0
	else
		echo -e "\e[31mErrors found\e[0m"
		exit 1
fi
